spring.application.name=tecsys

spring.profiles.active=postgres

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

jwt.secret=${JWT_SECRET:}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

server.port=8080
